In [ ]:
#This is a draft notebook, everything here is transposed to the src part

In [ ]:
import pandas as pd

In [90]:
def clean_columns(df):
    df = df.copy()
    columns = df.columns
    new_columns = []
    for i in columns:
        new_columns.append(
            i.strip().replace("(", "_").strip(")").lower().strip().replace("mileage_", "").replace("_cm3", "")
        )
    df.columns = new_columns
    return df

def replace_data(df):
    df = df.copy()
    df.drive_unit = df.drive_unit.replace({
        "rear drive" : "rear-wheel drive",
    })
    df.transmission = df.transmission.replace({
        "mechanics" : "manual",
        "auto" : "automatic"
    })

    df.condition = df.condition.replace({
        "with mileage": "with kilometrage"
    })

    df.fuel_type = df.fuel_type.replace({
        "electrocar" : "electric",
        "petrol" : "gasoline"
    })
    return df

def convert_dtypes(df):
    df = df.copy()
    df.kilometers = df.kilometers.replace([float('inf'), float('-inf')], pd.NA)
    df.volume     = df.volume.replace([float('inf'), float('-inf')], pd.NA)
    df.kilometers = df.kilometers.round().astype("Int64")
    df.volume     = df.volume.round().astype("Int64")

    return df 


def clean_volume(df):
    df = df.copy()
    df.volume = df.volume // 1000
    return df

In [ ]:
df = pd.read_csv("../data/cars.csv")

In [91]:
df.condition.unique()

<StringArray>
['with mileage', 'with damage', 'for parts']
Length: 3, dtype: str

In [92]:
def clean_df(df):
    return (
        df.pipe(clean_columns)
        .pipe(clean_volume)
        .pipe(replace_data)
        .pipe(convert_dtypes)
    )

df = df.pipe(clean_df)
df.segment.unique()

<StringArray>
['B', 'C', nan, 'M', 'D', 'E', 'A', 'J', 'S', 'F']
Length: 10, dtype: str

In [93]:
df.columns

Index(['make', 'model', 'priceusd', 'year', 'condition', 'kilometers',
       'fuel_type', 'volume', 'color', 'transmission', 'drive_unit',
       'segment'],
      dtype='str')

In [94]:
df.transmission.unique()

<StringArray>
['manual', 'automatic']
Length: 2, dtype: str

In [95]:
df.volume.unique()

<IntegerArray>
[1, 2, 20, 3, 16, 0, 4, 18, <NA>, 14, 13, 19, 12, 10, 5, 15, 6, 17, 9, 7, 8]
Length: 21, dtype: Int64

In [96]:
df.dtypes

make              str
model             str
priceusd        int64
year            int64
condition         str
kilometers      Int64
fuel_type         str
volume          Int64
color             str
transmission      str
drive_unit        str
segment           str
dtype: object

In [97]:
df

,make,model,priceusd,year,condition,kilometers,fuel_type,volume,color,transmission,drive_unit,segment
0,mazda,2,5500,2008,with kilometrage,162000,gasoline,1,burgundy,manual,front-wheel drive,B
1,mazda,2,5350,2009,with kilometrage,120000,gasoline,1,black,manual,front-wheel drive,B
2,mazda,2,7000,2009,with kilometrage,61000,gasoline,1,silver,automatic,front-wheel drive,B
3,mazda,2,3300,2003,with kilometrage,265000,diesel,1,white,manual,front-wheel drive,B
4,mazda,2,5200,2008,with kilometrage,97183,diesel,1,gray,manual,front-wheel drive,B
...,...,...,...,...,...,...,...,...,...,...,...,...
56239,lancia,zeta,3650,2000,with kilometrage,290000,gasoline,2,other,manual,front-wheel drive,M
56240,lancia,zeta,4100,1999,with kilometrage,340000,diesel,2,blue,manual,front-wheel drive,M
56241,lancia,zeta,3600,1997,with kilometrage,354000,diesel,2,burgundy,manual,front-wheel drive,M
56242,lancia,zeta,3000,1997,with kilometrage,350000,gasoline,2,blue,manual,front-wheel drive,M
56243,lancia,zeta,2950,1996,with kilometrage,3,gasoline,2,burgundy,manual,front-wheel drive,M

In [98]:
df.fuel_type.unique()

<StringArray>
['gasoline', 'diesel', 'electric']
Length: 3, dtype: str

In [99]:
df.kilometers.max()

np.int64(9999999)

In [103]:
import pandas as pd

df = pd.read_csv("../data/prepared_cars.csv")

In [104]:
df.describe()

            priceusd          year    kilometers        volume
count   56244.000000  56244.000000  5.624400e+04  56197.000000
mean     7415.456440   2003.454840  2.443956e+05      1.687119
std      8316.959261      8.144247  3.210307e+05      1.050707
min        48.000000   1910.000000  0.000000e+00      0.000000
25%      2350.000000   1998.000000  1.370000e+05      1.000000
50%      5350.000000   2004.000000  2.285000e+05      1.000000
75%      9807.500000   2010.000000  3.100000e+05      2.000000
max    235235.000000   2019.000000  9.999999e+06     20.000000

In [105]:
df

,make,model,priceusd,year,condition,kilometers,fuel_type,volume,color,transmission,drive_unit,segment
0,mazda,2,5500,2008,with kilometrage,162000,gasoline,1.0,burgundy,manual,front-wheel drive,B
1,mazda,2,5350,2009,with kilometrage,120000,gasoline,1.0,black,manual,front-wheel drive,B
2,mazda,2,7000,2009,with kilometrage,61000,gasoline,1.0,silver,automatic,front-wheel drive,B
3,mazda,2,3300,2003,with kilometrage,265000,diesel,1.0,white,manual,front-wheel drive,B
4,mazda,2,5200,2008,with kilometrage,97183,diesel,1.0,gray,manual,front-wheel drive,B
...,...,...,...,...,...,...,...,...,...,...,...,...
56239,lancia,zeta,3650,2000,with kilometrage,290000,gasoline,2.0,other,manual,front-wheel drive,M
56240,lancia,zeta,4100,1999,with kilometrage,340000,diesel,2.0,blue,manual,front-wheel drive,M
56241,lancia,zeta,3600,1997,with kilometrage,354000,diesel,2.0,burgundy,manual,front-wheel drive,M
56242,lancia,zeta,3000,1997,with kilometrage,350000,gasoline,2.0,blue,manual,front-wheel drive,M
56243,lancia,zeta,2950,1996,with kilometrage,3,gasoline,2.0,burgundy,manual,front-wheel drive,M

In [107]:
def create_age(df):
    df = df.copy()
    df.year = 2019 - df.year # deoarece anul maxim e 2019
    return df

def rename_columns(df):
    df = df.copy()
    df = df.rename(columns = {
        "year" : "car_age"
    })
    return df

In [108]:
def create_features(df):
    return (
        df.pipe(create_age)
        .pipe(rename_columns)
    )

In [109]:
df = df.pipe(create_features)

In [110]:
df

,make,model,priceusd,car_age,condition,kilometers,fuel_type,volume,color,transmission,drive_unit,segment
0,mazda,2,5500,11,with kilometrage,162000,gasoline,1.0,burgundy,manual,front-wheel drive,B
1,mazda,2,5350,10,with kilometrage,120000,gasoline,1.0,black,manual,front-wheel drive,B
2,mazda,2,7000,10,with kilometrage,61000,gasoline,1.0,silver,automatic,front-wheel drive,B
3,mazda,2,3300,16,with kilometrage,265000,diesel,1.0,white,manual,front-wheel drive,B
4,mazda,2,5200,11,with kilometrage,97183,diesel,1.0,gray,manual,front-wheel drive,B
...,...,...,...,...,...,...,...,...,...,...,...,...
56239,lancia,zeta,3650,19,with kilometrage,290000,gasoline,2.0,other,manual,front-wheel drive,M
56240,lancia,zeta,4100,20,with kilometrage,340000,diesel,2.0,blue,manual,front-wheel drive,M
56241,lancia,zeta,3600,22,with kilometrage,354000,diesel,2.0,burgundy,manual,front-wheel drive,M
56242,lancia,zeta,3000,22,with kilometrage,350000,gasoline,2.0,blue,manual,front-wheel drive,M
56243,lancia,zeta,2950,23,with kilometrage,3,gasoline,2.0,burgundy,manual,front-wheel drive,M

In [114]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

df = pd.read_csv("../data/featured_cars.csv")

In [115]:
df

,make,model,priceusd,car_age,condition,kilometers,fuel_type,volume,color,transmission,drive_unit,segment
0,mazda,2,5500,11,with kilometrage,162000,gasoline,1.0,burgundy,manual,front-wheel drive,B
1,mazda,2,5350,10,with kilometrage,120000,gasoline,1.0,black,manual,front-wheel drive,B
2,mazda,2,7000,10,with kilometrage,61000,gasoline,1.0,silver,automatic,front-wheel drive,B
3,mazda,2,3300,16,with kilometrage,265000,diesel,1.0,white,manual,front-wheel drive,B
4,mazda,2,5200,11,with kilometrage,97183,diesel,1.0,gray,manual,front-wheel drive,B
...,...,...,...,...,...,...,...,...,...,...,...,...
56239,lancia,zeta,3650,19,with kilometrage,290000,gasoline,2.0,other,manual,front-wheel drive,M
56240,lancia,zeta,4100,20,with kilometrage,340000,diesel,2.0,blue,manual,front-wheel drive,M
56241,lancia,zeta,3600,22,with kilometrage,354000,diesel,2.0,burgundy,manual,front-wheel drive,M
56242,lancia,zeta,3000,22,with kilometrage,350000,gasoline,2.0,blue,manual,front-wheel drive,M
56243,lancia,zeta,2950,23,with kilometrage,3,gasoline,2.0,burgundy,manual,front-wheel drive,M

In [ ]:
TARGET_COLUMN = "priceUSD"

ORDINAL_FEATURES = [
    "transmission",
    "drive_unit",
]

In [118]:
df.transmission.unique()

<StringArray>
['manual', 'automatic']
Length: 2, dtype: str

In [121]:
df.drive_unit.unique()

<StringArray>
[         'front-wheel drive',                          nan,
           'rear-wheel drive',            'all-wheel drive',
 'part-time four-wheel drive']
Length: 5, dtype: str

In [ ]:
ORDINAL_CATEGORIES = [
    ["manual", "automatic"],
    ["front-wheel drive", "rear-wheel drive", "all-wheel drive", "part-time four-wheel drive"]
]

In [120]:
df.drive_unit.unique()

<StringArray>
[         'front-wheel drive',                          nan,
           'rear-wheel drive',            'all-wheel drive',
 'part-time four-wheel drive']
Length: 5, dtype: str

In [ ]:
CATEGORICAL_FEATURES = [
    "condition",
    "color",
    "segment",
    "fuel_type",
    "make",
    "model",
]

In [ ]:
NUMERICAL_FEATURES = [
    "car_age",
    "kilometers",
    "volume"
]

In [ ]:

def get_all_features():
    return ORDINAL_FEATURES + CATEGORICAL_FEATURES + NUMERICAL_FEATURES

def split_the_features_and_target(df):
    X = df[get_all_features()].copy()
    y = df[TARGET_COLUMN].copy()

    return X, y 

def _build_categorical_pipeline():
    categorical_pipeline_t = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown = "ignore", sparse_output = False))
        ]
    )

    return categorical_pipeline_t

def _build_ordinal_pipeline():
    ordinal_pipeline_t = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "most_frequent")),
            ("ordinal", OrdinalEncoder(categories = ORDINAL_CATEGORIES, handle_unknown="use_encoded_value", unknown_value=-1))
        ]
    )

    return ordinal_pipeline_t

def _build_numeric_pipeline():
    numeric_pipeline_t = Pipeline(
        steps = [
            ("imputer", SimpleImputer(strategy = "median")),
            ("scaler", StandardScaler())
        ]
    )
    return numeric_pipeline_t

def build_processor():
    preprocessor = ColumnTransformer(
        transformers = [
            ("num", _build_numeric_pipeline(), NUMERICAL_FEATURES),
            ("ord", _build_ordinal_pipeline(), ORDINAL_FEATURES),
            ("cat", _build_categorical_pipeline(), CATEGORICAL_FEATURES)
        ],
        remainder = "drop" 
    )
    return preprocessor

In [2]:
import pandas as pd
df = pd.read_csv("../data/featured_cars.csv")

In [4]:
df.head(2)

,make,model,priceusd,car_age,condition,kilometers,fuel_type,volume,color,transmission,drive_unit,segment
0,mazda,2,5500,11,with kilometrage,162000,gasoline,1.0,burgundy,manual,front-wheel drive,B
1,mazda,2,5350,10,with kilometrage,120000,gasoline,1.0,black,manual,front-wheel drive,B

In [9]:
df.color.unique()

<StringArray>
['burgundy',    'black',   'silver',    'white',     'gray',     'blue',
    'other',   'purple',      'red',    'green',    'brown',   'yellow',
   'orange']
Length: 13, dtype: str

In [15]:
df.shape

(56244, 12)

In [21]:
df[(df.priceusd <= 100_000) & (df.priceusd >=500)].count()

make            54882
model           54882
priceusd        54882
car_age         54882
condition       54882
kilometers      54882
fuel_type       54882
volume          54838
color           54882
transmission    54882
drive_unit      53072
segment         49765
dtype: int64

In [22]:

df = pd.read_csv("../data/featured_cars.csv")

In [23]:
df

,make,priceusd,car_age,condition,kilometers,fuel_type,volume,transmission,drive_unit,segment
0,mazda,5500,11,with kilometrage,162000,gasoline,1.0,manual,front-wheel drive,B
1,mazda,5350,10,with kilometrage,120000,gasoline,1.0,manual,front-wheel drive,B
2,mazda,7000,10,with kilometrage,61000,gasoline,1.0,automatic,front-wheel drive,B
3,mazda,3300,16,with kilometrage,265000,diesel,1.0,manual,front-wheel drive,B
4,mazda,5200,11,with kilometrage,97183,diesel,1.0,manual,front-wheel drive,B
...,...,...,...,...,...,...,...,...,...,...
56239,lancia,3650,19,with kilometrage,290000,gasoline,2.0,manual,front-wheel drive,M
56240,lancia,4100,20,with kilometrage,340000,diesel,2.0,manual,front-wheel drive,M
56241,lancia,3600,22,with kilometrage,354000,diesel,2.0,manual,front-wheel drive,M
56242,lancia,3000,22,with kilometrage,350000,gasoline,2.0,manual,front-wheel drive,M
56243,lancia,2950,23,with kilometrage,3,gasoline,2.0,manual,front-wheel drive,M

In [25]:
df.make.unique()

<StringArray>
[         'mazda',             'mg',        'renault',            'gaz',
            'aro',          'rover',            'uaz',     'alfa-romeo',
           'audi',     'oldsmobile',           'saab',        'peugeot',
       'chrysler',       'wartburg',       'moskvich',          'volvo',
           'fiat',          'roewe',        'porsche',            'zaz',
           'luaz',          'dacia',       'lada-vaz',            'izh',
            'raf',         'bogdan',            'bmw',         'nissan',
  'mercedes-benz',     'mitsubishi',         'toyota',          'chery',
            'gmc',        'hyundai',          'honda',      'ssangyong',
         'suzuki',           'opel',           'seat',     'volkswagen',
       'daihatsu',      'chevrolet',          'geely',         'saturn',
            'kia',        'lincoln',     'eksklyuziv',        'citroen',
      'dong-feng',        'pontiac',           'ford',         'subaru',
        'bentley',            'faw',       'cadillac',          'lifan',
       'plymouth',          'hafei', 'shanghai-maple',           'mini',
           'jeep',          'skoda',        'mercury',        'changan',
          'lexus',          'isuzu',   'aston-martin',         'lancia',
     'great-wall',     'land-rover',         'jaguar',          'buick',
         'daewoo',         'vortex',       'infiniti',            'byd',
          'smart',       'maserati',          'haval',          'acura',
          'scion',           'tata',         'datsun',          'tesla',
        'mclaren',          'ravon',        'trabant',         'proton',
            'fso',            'jac',           'asia',    'iran-khodro',
          'zotye',          'tagaz',          'saipa',     'brilliance']
Length: 96, dtype: str

In [ ]:
["mclaren", "mercedes-benz", "tesla", "maserati", "aston-martin", "bentley", "bmw", "porche", "audi"],